# -*- coding: utf-8 -*-
"""AutoMoblie.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Glihkl3P0BGV7JWbvBBJkaHHR_veTBFE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Automobile_data.csv")
print(df)

print(df.head())

print(df.tail())

print(df.columns)

print(df.isnull().sum())

print(df.dtypes)

print(df.describe())

#Exploratory Data Analysis
sns.countplot(x='city-mpg', data=df)
plt.title("city-mpg")
plt.show()

sns.countplot(x='price', data=df)
plt.title("Price Distribution")
plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(df.corr(numeric_only=True),
            annot=True,
            cmap='coolwarm')

plt.title("Correlation Matrix")
plt.show()

sns.countplot(x='drive-wheels', data=df)
plt.title("Wheels")
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df['price'], bins=20, kde=True)
plt.title("Price Distribution")
plt.show()

#Identifying Attributes
print("\nNumeric Attributes")
numeric = df.select_dtypes(include=['int64','float64']).columns
print(numeric)

print("\nNominal Attributes")
nominal = ['horsepower','peak-rpm ']
print(nominal)

sns.countplot(x='num-of-doors', data=df)
plt.title("Doors")
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(df['city-mpg'], bins=20, kde=True)
plt.title("City MPG Distribution")
plt.show()

print("\nNumeric Attributes")
numeric = df.select_dtypes(include=['int64', 'float64']).columns
print(numeric)

make = df['make']
fuel = df['fuel-type']

count = 0
total = 0

for m, f in zip(make, fuel):

    if pd.isna(m) or pd.isna(f):
        continue

    total += 1

    if m != f:
        count += 1

dissimilarity = count / total

print("\nNominal Attribute Dissimilarity")
print("Make vs Fuel-Type =", dissimilarity)

temp = df[['horsepower', 'price']].dropna()

# Convert 'horsepower' and 'price' to numeric, coercing errors
temp['horsepower'] = pd.to_numeric(temp['horsepower'], errors='coerce')
temp['price'] = pd.to_numeric(temp['price'], errors='coerce')

# Drop rows where conversion resulted in NaN
temp = temp.dropna()

hp1 = temp.iloc[0]['horsepower']
price1 = temp.iloc[0]['price']

hp2 = temp.iloc[1]['horsepower']
price2 = temp.iloc[1]['price']

# Euclidean Distance
distance = np.sqrt((hp1 - hp2)**2 + (price1 - price2)**2)
print("\nEuclidean Distance")
print(distance)

# Manhattan Distance
manhattan = abs(hp1 - hp2) + abs(price1 - price2)
print("\nManhattan Distance")
print(manhattan)

# Minkowski Distance (p = 3)
Minkowski = ((abs(hp1 - hp2)**3) + (abs(price1 - price2)**3))**(1/3)
print("\nMinkowski Distance")
print(Minkowski)

# Cosine Dissimilarity
A = np.array([hp1, price1])
B = np.array([hp2, price2])
cosine_similarity = np.dot(A, B) / (
    np.linalg.norm(A) * np.linalg.norm(B)
)
cosine_dissimilarity = 1 - cosine_similarity
print("\nCosine Dissimilarity")
print(cosine_dissimilarity)